[package]
name = 'bash-object'
slug = 'bash_object'
version = '0.1.0'
authors = ['Edwin Kofler" <edwin@kofler.dev>']

[layout]
binDirs = ['./pkg/bin']

[requirements]
dependencies = ['ztombol/bats-support@v0.3.0', 'ztombol/bats-assert@v0.3.0']
