[package]
name = 'bash-object'
slug = 'bash_object'
version = '0.7.0'
authors = ['Edwin Kofler" <edwin@kofler.dev>']

[run]
dependencies = ['https://github.com/hyperupcall/bats-common-utils.git@v3.0.0']
sourceDirs = ['pkg/src', 'pkg/src/public', 'pkg/src/util']
builtinDirs = []
binDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]

[run.shoptOptions]
