[package]
name = 'bash-object'
slug = 'bash_object'
version = '0.8.0'
authors = ['Edwin Kofler" <edwin@kofler.dev>']

[run]
dependencies = ['https://github.com/hyperupcall/bats-all.git@v4.2.0']
sourceDirs = ['pkg/src', 'pkg/src/public', 'pkg/src/util']
builtinDirs = []
binDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]
errexit = 'on'
pipefail = 'on'

[run.shoptOptions]
shift_verbose = 'on'
