using = ["Bash"]
project = "bash-object"
description = "Bash library for object oriented data"
license = 'Apache-2.0'


gitRepoName = 'bash-object'
distroPackageName = 'glue'

name = "Edwin Kofler"
email = "edwin@kofler.dev"

gitRemoteUser = 'eankeen'
gitRemoteRepo = 'bash-object'

[system]
glueVersion = 'be3110e397ae4d39266b3ec5f6b2c287392578ab'

programVersion = '0.7.0+916ca13-DIRTY'
