using = ["Bash", "Docker"]
project = "bash-args"
description = "A cute little Bash library for blazing fast argument parsing"
license = 'Apache-2.0'


gitRepoName = 'bash-args'
distroPackageName = 'glue'

name = "Edwin Kofler"
email = "edwin@kofler.dev"

gitRemoteUser = 'eankeen'
gitRemoteRepo = 'bash-args'
