using = ["Bash"]
project = "bash-object"
description = "Bash library for object oriented data"
license = 'Apache-2.0'


gitRepoName = 'bash-object'
distroPackageName = 'glue'

name = "Edwin Kofler"
email = "edwin@kofler.dev"

gitRemoteUser = 'eankeen'
gitRemoteRepo = 'bash-object'
