# shellcheck shell=bash

load './util/init.sh'

@test "Error if random variable already exists" {
	bash_object.util.generate_vobject_name() {
		REPLY="some_other_var"
	}
	declare -g some_other_var=

	run bash_object.traverse-set object 'OBJECT' '.obj' obj

	assert_failure
	assert_output -p 'ERROR_INTERNAL_MISCELLANEOUS'
	assert_output -p "Autogenerated variable 'some_other_var' already exists"
}
