[package]
type = 'bash'
name = 'bash-object-example'
slug = 'bash_object_example'
version = '0.1.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'Example for bash_object'

[run]
dependencies = ['https://github.com/hyperupcall/bash-object.git@fa3162d802a0b8270422b106115bfb14e51087af'] # v0.8.0
sourceDirs = []
builtinDirs = []
binDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]

[run.shoptOptions]
