name: 'Website'

on:
  push:
    branches-ignore: ['*-no-ci']
    tags-ignore: ['*']

permissions:
  contents: 'read'
  pages: 'write'
  id-token: 'write'

jobs:
  build-and-deploy:
    name: 'Build And Deploy'
    uses: 'fox-land/hyperupcall-action/.github/workflows/website.yml@main'
